/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as petSol from "./Pet.sol";
export type { petSol };
export type { Auction } from "./Auction";
export type { Bank } from "./Bank";
export type { PETICO } from "./PETICO";
export type { PetShopee } from "./PetShopee";
export type { PetToken } from "./PetToken";
export type { SimpleToken } from "./SimpleToken";
